#开发环境配置
spring:
  datasource:
    hikari:
      mpdrivermaster:
        name: dev
        jdbc-url: jdbc:mysql://mysql-m-wr-car-all-dev-new-db.01zhuanche.com:3307/mp_driver?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
         #最小空闲连接数量
        minimum-idle: 5
        #空闲连接存活最大时间，默认600000（10分钟
        idle-timeout: 300000
        #连接池最大连接数，默认是50
        maximum-pool-size: 50
        #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        #pool-name
        pool-name: master_mpDriver_HikariCP
        #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 1800000
        #数据库连接超时时间,默认30秒，即30000
        connection-timeout: 300000
        connection-test-query: SELECT 1
      mpdriverslave:
        name: dev
        jdbc-url: jdbc:mysql://mysql-s-ro-car-all-dev-new-db.01zhuanche.com:3307/mp_driver?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_mdbCarManager_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      mdbcarmanagemaster:
        name: dev
        jdbc-url: jdbc:mysql://mysql-m-wr-car-all-dev-new-db.01zhuanche.com:3307/MDB_CAR_MANAGE?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: master_mdbCarManager_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      mdbcarmanageslave:
        name: dev
        jdbc-url: jdbc:mysql://mysql-s-ro-car-all-dev-new-db.01zhuanche.com:3307/MDB_CAR_MANAGE?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_mdbCarManager_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      driversparkmaster:
        name: dev
        jdbc-url: jdbc:mysql://mysql-m-wr-car-all-dev-new-db.01zhuanche.com:3307/driver_spark?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: master_driverSpark_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      driversparkslave:
        name: dev
        jdbc-url: jdbc:mysql://mysql-s-ro-car-all-dev-new-db.01zhuanche.com:3307/driver_spark?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_driverSpark_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    pool:
      max-active: 200
      max-idle: 50
    cluster:
      nodes: redis-cluster-c1-car-all-dev-new-db.01zhuanche.com:6381,redis-cluster-c2-car-all-dev-new-db.01zhuanche.com:6381,redis-cluster-c3-car-all-dev-new-db.01zhuanche.com:6381,redis-cluster-c4-car-all-dev-new-db.01zhuanche.com:6380,redis-cluster-c5-car-all-dev-new-db.01zhuanche.com:6380,redis-cluster-c6-car-all-dev-new-db.01zhuanche.com:6380
    password: qBa39fA&?@-o

#sso redis 配置
#  redis.sentinel.name=test
#  redis.server1.host=10.20.10.100
#  redis.server1.port=26379
#  redis.server2.host=10.20.10.101
#  redis.server2.port=26379
#  redis.server3.host=10.20.10.102
#  redis.server3.port=26379
#  redis.maxActive=120
#  redis.maxIdle=60
#  redis.maxWait=2000
#  redis.testOnBorrow=true
#  redis.password=

okhttp:
  client:
    connections:
    -
      clientName: client3
      connectTimeout: 100
      readTimeout: 100
      writeTimeout: 100
      maxIdleConnections: 100
      keepAliveDuration: 5
      maxRetry: 3
      logParamsSwitch: false
      logIgnore: true
      enalbeHttps: true

zuul:
  routes:
    chargeapi:
      path: /charge/**
      url: http://dev-inside-saas-charge.guobindui.cn/charge/
    orderapi:
      path: /order/**
      url: http://dev-inside-order-spark.guobindui.cn/order/
    dispatchapi:
      path: /dispatch/**
      url: http://dev-inside-spark-dispatch-cms.guobindui.cn/
    mpapi:
      path: /mp/**
      url: http://dev-inside-mp-spark-manage.guobindui.cn/
    thirdapi:
      path: /uploadPhoto/**
      url: http://dev-inside-mp.01zhuanche.com/uploadPhoto/

#钉钉报警开关
ding.ding.switch: false
#钉钉报警url
ding.ding.monitor.url: https://oapi.dingtalk.com/robot/send?access_token=adba3f805eeaec5d6b87f85d7cd93b850aa6055d54a4079a87e2d79b2265746d


auth.finduser.url: http://test-inside-auth.01zhuanche.com/findUser.html

auth.permission.url: http://test-inside-auth.01zhuanche.com/findPermission.html
#应该是用不到
auth.appid: 18

resetpassword.msgnotify.switch: false
user.password.indexOfPhone: 9,5,3,7,1,4,8,2
login.checkMsgCode.switch: false

loginpage.url: https://dev-saas.guobindui.cn/

homepage.url: https://dev-saas.guobindui.cn/#/Manage

login.url: https://dev-saas-spark.guobindui.cn/login

#短信发送相关
short_message_url: http://test-inside-mp.01zhuanche.com/api/v1/message/content/send
short_message_appkey: 04F934A9C93E4376ACC51CBE4B5FDCCC
short_message_appsecret: B89E2C9C203D4CAE88383431A2C4CC6E
template_short_message_url: http://test-inside-mp.01zhuanche.com/api/v1/message/template/send
