#开发环境配置
spring:
  datasource:
    hikari:
      driversparkmaster:
        name: dev
        jdbc-url: jdbc:mysql://mysql-m-wr-car-all-dev-new-db.01zhuanche.com:3307/driver_spark?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: master_driverSpark_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      driversparkslave:
        name: dev
        jdbc-url: jdbc:mysql://mysql-s-ro-car-all-dev-new-db.01zhuanche.com:3307/driver_spark?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: dev_sqhc_rentcar
        password: dev_BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_driverSpark_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    pool:
      max-active: 200
      max-idle: 50
    cluster:
      nodes: redis-cluster-c1-car-all-dev-new-db.01zhuanche.com:6381,redis-cluster-c2-car-all-dev-new-db.01zhuanche.com:6381,redis-cluster-c3-car-all-dev-new-db.01zhuanche.com:6381,redis-cluster-c4-car-all-dev-new-db.01zhuanche.com:6380,redis-cluster-c5-car-all-dev-new-db.01zhuanche.com:6380,redis-cluster-c6-car-all-dev-new-db.01zhuanche.com:6380
    password: qBa39fA&?@-o

zuul:
  routes:
    chargeapi:
      path: /charge/**
      url: http://dev-inside-saas-charge.guobindui.cn/charge/
    orderapi:
      path: /order/**
      url: http://dev-inside-order-spark.guobindui.cn/order/
    dispatchapi:
      path: /dispatch/**
      url: http://dev-inside-spark-dispatch-cms.guobindui.cn/
    mpapi:
      path: /mp/**
      url: http://dev-inside-mp-spark-manage.guobindui.cn/
    uploadPhoto:
      path: /common/uploadPhoto/**
      url: http://dev-inside-mp.01zhuanche.com/v1/driver/uploadPhoto/
    thirdapi:
      path: /common/upload/**
      url: http://dev-inside-third-api.01zhuanche.com/file/upload
    shareapi:
      path: /share/**
      url: http://dev-inside-saas-share.guobindui.cn/share/
    kfapi:
      path: /kefu/**
      url: http://dev-inside-cs-spark-manage.guobindui.cn/api/web/
    company:
      path: /api/inside/**
      url: http://dev-inside-bigdata-athena.01zhuanche.com

#钉钉报警开关
ding.ding.switch: false
#钉钉报警url
ding.ding.monitor.url: https://oapi.dingtalk.com/robot/send?access_token=adba3f805eeaec5d6b87f85d7cd93b850aa6055d54a4079a87e2d79b2265746d


auth.finduser.url: http://test-inside-auth.01zhuanche.com/findUser.html

auth.permission.url: http://test-inside-auth.01zhuanche.com/findPermission.html
#应该是用不到
auth.appid: 18

resetpassword.msgnotify.switch: false
user.password.indexOfPhone: 9,5,3,7,1,4,8,2
login.checkMsgCode.switch: false

loginpage.url: https://dev-saas.guobindui.cn/

homepage.url: https://dev-saas.guobindui.cn/#/Manage

login.url: https://dev-saas.guobindui.cn/signin

#没有权限地址
unauthorized.url: https://dev-saas.guobindui.cn/unauthorized

#短信发送相关
short_message_url: http://test-inside-mp.01zhuanche.com/api/v1/message/content/send
short_message_appkey: 04F934A9C93E4376ACC51CBE4B5FDCCC
short_message_appsecret: B89E2C9C203D4CAE88383431A2C4CC6E
template_short_message_url: http://test-inside-mp.01zhuanche.com/api/v1/message/template/send


#h5找回密码域名
reset.password.url: https://dev-saas.guobindui.cn/forgot?email=

