#生产环境配置
spring:
  datasource:
    hikari:
      mpdrivermaster:
        name: online
        jdbc-url: jdbc:mysql://SJ-mysql-m-wr-car-mp-online-vip-db.01zhuanche.com:5370/mp_driver?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=1000&socketTimeout=15000
        username: mp_driver
        password: mp_driver@01zhuanche.com
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: master_mpdriver_hikaricp
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      mpdriverslave:
        name: online
        jdbc-url: jdbc:mysql://SJ-mysql-s-ro-car-mp-online-f5-db.01zhuanche.com:5370/mp_driver?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=1000&socketTimeout=15000
        username: mp_driver
        password: mp_driver@01zhuanche.com
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_mpdriver_hikaricp
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      rentcarmaster:
        name: online
        jdbc-url: jdbc:mysql://SJ-mysql-m-wr-car-rentcar-online-order-vip-db.01zhuanche.com:5310/rentcar?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&connectTimeout=1000&socketTimeout=15000
        username: sqhc_rentcar
        password: BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: master_rentcar_hikaricp
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      rentcarslave:
        name: online
        jdbc-url: jdbc:mysql://SJ-mysql-s-ro-car-rentcar-online-background-lvs-db.01zhuanche.com:5310/rentcar?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&connectTimeout=1000&socketTimeout=15000
        username: sqhc_rentcar
        password: BzkmQM%O^U7Dy8X3
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_rentcar_hikaricp
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      driversparkmaster:
        name: dev
        jdbc-url: jdbc:mysql://mysql-m5353-driver-spark-online.yongxinchuxing.com:5353/driver_spark?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: mp_manage_web
        password: EOp!hEjUAamIIC4B
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: master_driverSpark_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      driversparkslave:
        name: dev
        jdbc-url: jdbc:mysql://mysql-s5353-driver-spark-online.yongxinchuxing.com:5353/driver_spark?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectTimeout=1000&amp;socketTimeout=15000
        username: mp_manage_web
        password: EOp!hEjUAamIIC4B
        minimum-idle: 5
        idle-timeout: 300000
        maximum-pool-size: 50
        auto-commit: true
        pool-name: slave_driverSpark_HikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    pool:
      max-active: 200
      max-idle: 50
    cluster:
      nodes: redis-c7021-n1-driver-spark-online.yongxinchuxing.com:7021,redis-c7021-n2-driver-spark-online.yongxinchuxing.com:7021,redis-c7021-n3-driver-spark-online.yongxinchuxing.com:7021,redis-c7021-n4-driver-spark-online.yongxinchuxing.com:7021,redis-c7021-n5-driver-spark-online.yongxinchuxing.com:7021,redis-c7021-n6-driver-spark-online.yongxinchuxing.com:7021
    password: AcomCdgN05srE

zuul:
  routes:
    chargeapi:
      path: /charge/**
      url: http://inside-saas-charge.yongxinchuxing.com/charge/
    orderapi:
      path: /order/**
      url: http://inside-order-spark.yongxinchuxing.com/order/
    dispatchapi:
      path: /dispatch/**
      url: http://inside-spark-dispatch-cms.yongxinchuxing.com/
    mpapi:
      path: /mp/**
      url: http://inside-mp-spark-manage.yongxinchuxing.com/
    uploadPhoto:
      path: /common/uploadPhoto/**
      url: http://inside-mp.01zhuanche.com/v1/driver/uploadPhoto/
    thirdapi:
      path: /common/upload/**
      url: http://inside-third-api.01zhuanche.com/file/upload
    shareapi:
      path: /share/**
      url: http://inside-saas-share.yongxinchuxing.com/share/
    kfapi:
      path: /kefu/**
      url: http://inside-cs-spark-manage.yongxinchuxing.com/api/web/
    company:
      path: /api/inside/**
      url: http://inside-bigdata-athena.01zhuanche.com/api/inside/
    activity:
      path: /sparkActivity/**
      url: http://inside-spark-activity.yongxinchuxing.com/sparkActivity/
    pay:
      path: /pay/**
      url: http://inside-pay.01zhuanche.com/pay/
    lbs:
      path: /lbs/**
      url: http://inside-spark-base-lbs.yongxinchuxing.com/lbs/
    usercenter:
      path: /usercenter/admin/**
      url: http://inside-spark-mp-usercenter.yongxinchuxing.com/admin/
#钉钉报警开关
ding.ding.switch: false
#钉钉报警url
ding.ding.monitor.url: https://oapi.dingtalk.com/robot/send?access_token=adba3f805eeaec5d6b87f85d7cd93b850aa6055d54a4079a87e2d79b2265746d

#应该是用不到

auth.finduser.url: http://inside-auth.01zhuanche.com/findUser.html

auth.permission.url: http://inside-auth.01zhuanche.com/findPermission.html

auth.appid: 18

resetpassword.msgnotify.switch: true
user.password.indexOfPhone: 9,5,3,7,1,4,8,2
login.checkMsgCode.switch: true

loginpage.url: https://saas.yongxinchuxing.com/

homepage.url: https://saas.yongxinchuxing.com/#/Manage

login.url: https://saas-spark.yongxinchuxing.com/signin

#没有权限地址
unauthorized.url: https://saas.yongxinchuxing.com/unauthorized
#选择商户页面
query.merchant.url: https://dev-saas.yongxinchuxing.com/signin


#短信发送相关
short_message_url: http://inside-mp.01zhuanche.com/api/v1/message/content/send
short_message_appkey: 04F934A9C93E4376ACC51CBE4B5FDCCC
short_message_appsecret: B89E2C9C203D4CAE88383431A2C4CC6E
template_short_message_url: http://inside-mp.01zhuanche.com/api/v1/message/template/send


#h5找回密码域名
reset.password.url: https://saas.yongxinchuxing.com/forgot?email=

kafka:
  client:
    services: 10.130.20.46:9092,10.130.20.64:9092,10.130.20.66:9092
    kafkaKeySerializer: org.apache.kafka.common.serialization.StringSerializer
    kafkaValueSerializer: org.apache.kafka.common.serialization.StringSerializer
    retries: 1
    batchSize: 4096
    lingerMs: 10
    bufferMemory: 40960
    acks: all
    defaultTopic: mp-kafka-user-logger

